#docker-compose.yml
version: '3'
services:
  web:
    container_name: web
    build: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db_web
    ports:
      - 8080:80
  db_web:
    image: mysql:8.0
    container_name: db_web
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kirim-email
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - 6037:3306
